### ISSUE TITLE
TypeError: get_pinyin() got an unexpected keyword argument 'show_tone_marks'

### ISSUE THREAD

**Issue by wujsy** [HappyBall/tacotron#3]
Hi, I have fallowed your steps and loaded the Lecture record Chinese dataset,  but encounted errors as fallows:
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    g = Graph(); 
  File "/data/workspace/tts/happyball/tacotron/graph.py", line 30, in __init__
    self.x, self.y, self.z, self.fnames, self.num_batch = get_batch()
  File "/data/workspace/tts/happyball/tacotron/data_load.py", line 346, in get_batch
    fpaths, text_lengths, texts = load_data() # list
  File "/data/workspace/tts/happyball/tacotron/data_load.py", line 204, in load_data
    text = to_bopomofo(text, tones=False)
  File "/usr/local/lib/python2.7/dist-packages/bopomofo/__init__.py", line 24, in to_bopomofo
    return splitter.join(_bopomofo_list(chars, tones, first_tone_symbol))
  File "/usr/local/lib/python2.7/dist-packages/bopomofo/__init__.py", line 44, in _bopomofo_list
    pinyin = _pinyin_list(chars, tones)
  File "/usr/local/lib/python2.7/dist-packages/bopomofo/__init__.py", line 38, in _pinyin_list
    return _pinyin.get_pinyin(chars, '|', show_tone_marks=tones).split('|')
TypeError: get_pinyin() got an unexpected keyword argument 'show_tone_marks'

what's the problem?

**Comment by wangmengmeng99** [comment]
这个问题是由于包的问题，新版本的show_tone_marks已经没有了，换成了tone_marks
